"""attachments added to prompt history

Revision ID: 16414c796805
Revises: d9003d3b3a73
Create Date: 2026-01-21 17:59:50.494021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16414c796805'
down_revision: Union[str, Sequence[str], None] = 'd9003d3b3a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_history_id', sa.Integer(), nullable=False),
    sa.Column('attachments_data', sa.Text(), nullable=True),
    sa.Column('generated_images', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_history_id'], ['prompt_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test_auth')
    op.add_column('categories', sa.Column('nav_settings', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('sessions_session_token_key'), 'sessions', type_='unique')
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.drop_constraint(op.f('sessions_user_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_weaviate_data_versions_changed_at'), table_name='weaviate_data_versions')
    op.drop_constraint(op.f('weaviate_data_versions_weaviate_data_id_fkey'), 'weaviate_data_versions', type_='foreignkey')
    op.create_foreign_key(None, 'weaviate_data_versions', 'weaviate_data', ['weaviate_data_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weaviate_data_versions', type_='foreignkey')
    op.create_foreign_key(op.f('weaviate_data_versions_weaviate_data_id_fkey'), 'weaviate_data_versions', 'weaviate_data', ['weaviate_data_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_weaviate_data_versions_changed_at'), 'weaviate_data_versions', ['changed_at'], unique=False)
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_user_id_fkey'), 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=False)
    op.create_unique_constraint(op.f('sessions_session_token_key'), 'sessions', ['session_token'], postgresql_nulls_not_distinct=False)
    op.drop_column('categories', 'nav_settings')
    op.create_table('test_auth',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('customer_app_ssuid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('app_registration_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expiry_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('grace_period', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_rental', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('product_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_auth_2_pkey'))
    )
    op.drop_table('prompt_attachments')
    # ### end Alembic commands ###
