"""Remove server_default from pages.updated_on column

Revision ID: 3110dc4c039d
Revises: 1382f70120a9
Create Date: 2025-12-17 18:20:21.986732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3110dc4c039d'
down_revision: Union[str, Sequence[str], None] = '1382f70120a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'updated_on',
                    existing_type=sa.DateTime(timezone=True),
                    server_default=None,
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'updated_on',
                    existing_type=sa.DateTime(timezone=True),
                    server_default=sa.func.now(),
                    existing_nullable=True)
    # ### end Alembic commands ###
