"""add_prompt_like_and_prompt_action_to_prompt_history

Revision ID: 38ea296bc428
Revises: 41723ff13bbb
Create Date: 2025-12-12 15:36:52.311843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ea296bc428'
down_revision: Union[str, Sequence[str], None] = '41723ff13bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first
    promptlikestatusenum = sa.Enum('UNLIKED', 'LIKED', 'NEUTRAL', name='promptlikestatusenum')
    promptlikestatusenum.create(op.get_bind(), checkfirst=True)
    
    promptactionenum = sa.Enum('NEW', 'DRAFT', 'RE_RUN', 'CANCEL', 'RESTORE', name='promptactionenum')
    promptactionenum.create(op.get_bind(), checkfirst=True)
    
    # Add columns with enum types
    op.add_column('prompt_history', sa.Column('prompt_like', promptlikestatusenum, nullable=True))
    op.add_column('prompt_history', sa.Column('prompt_action', promptactionenum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_history', 'prompt_action')
    op.drop_column('prompt_history', 'prompt_like')
    
    # Drop enum types
    sa.Enum(name='promptactionenum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='promptlikestatusenum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
