"""add_updated_on_to_weaviate_data

Revision ID: 390d4606e1f5
Revises: 441678425711
Create Date: 2025-12-15 17:32:34.646842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '390d4606e1f5'
down_revision: Union[str, Sequence[str], None] = '441678425711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weaviate_data', sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weaviate_data', 'updated_on')
    # ### end Alembic commands ###
