"""Add weaviate_data table

Revision ID: 441678425711
Revises: 38ea296bc428
Create Date: 2025-12-15 13:05:31.486984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441678425711'
down_revision: Union[str, Sequence[str], None] = '38ea296bc428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weaviate_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'CANCELLED', 'EXIT_WITH_ERROR', 'COMPLETED', name='weaviatedatastatusenum'), nullable=False),
    sa.Column('no_of_lines', sa.Integer(), nullable=True),
    sa.Column('no_of_tokens', sa.Integer(), nullable=True),
    sa.Column('no_of_characters', sa.Integer(), nullable=True),
    sa.Column('data_details', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weaviate_data_collection_name'), 'weaviate_data', ['collection_name'], unique=False)
    op.create_index(op.f('ix_weaviate_data_created_by'), 'weaviate_data', ['created_by'], unique=False)
    op.create_index(op.f('ix_weaviate_data_status'), 'weaviate_data', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weaviate_data_status'), table_name='weaviate_data')
    op.drop_index(op.f('ix_weaviate_data_created_by'), table_name='weaviate_data')
    op.drop_index(op.f('ix_weaviate_data_collection_name'), table_name='weaviate_data')
    op.drop_table('weaviate_data')
    # ### end Alembic commands ###
