"""modifications

Revision ID: 55341155edc3
Revises: 92b58e534f30
Create Date: 2025-12-11 13:03:04.588780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55341155edc3'
down_revision: Union[str, Sequence[str], None] = '92b58e534f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_session_id', sa.String(length=255), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('task_run_id', sa.Integer(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('prompt_type', sa.Enum('TEXT', 'IMAGE', 'VIDEO', 'AUDIO', 'MULTITYPE', name='prompttypeenum'), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_on', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_history_prompt_session_id'), 'prompt_history', ['prompt_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_history_prompt_session_id'), table_name='prompt_history')
    op.drop_table('prompt_history')
    # ### end Alembic commands ###
