"""create initial tables

Revision ID: 6c61e3ebe979
Revises: 
Create Date: 2025-12-10 13:43:54.159906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c61e3ebe979'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('is_parent', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_root', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_on', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_category_name'), 'categories', ['category_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwd', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_on', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('schedulers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scheduler_name', sa.String(length=255), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_on', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedulers_scheduler_name'), 'schedulers', ['scheduler_name'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('task_message', sa.Text(), nullable=True),
    sa.Column('scheduler_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_on', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scheduler_id'], ['schedulers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_task_name'), 'tasks', ['task_name'], unique=False)
    op.create_table('task_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('task_run_status', sa.Enum('PENDING', 'IN_PROGRESS', 'CANCELLED', 'COMPLETED', name='taskrunstatusenum'), nullable=False),
    sa.Column('task_run_message', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scheduled_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_runs_uuid'), 'task_runs', ['uuid'], unique=True)
    op.create_table('content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_run_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('prompt_data', sa.Text(), nullable=True),
    sa.Column('generated_content', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action', sa.Enum('DRAFT', 'RE_RUN', 'CANCEL', 'STOP', name='contentactionenum'), nullable=False),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'REVISION_NEEDED', name='contentapprovalstatusenum'), nullable=False),
    sa.Column('approval_status_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('quarter', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content')
    op.drop_index(op.f('ix_task_runs_uuid'), table_name='task_runs')
    op.drop_table('task_runs')
    op.drop_index(op.f('ix_tasks_task_name'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_schedulers_scheduler_name'), table_name='schedulers')
    op.drop_table('schedulers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_category_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
