"""Add source_url and scrapped_data to pages table

Revision ID: 8d90685dd4c5
Revises: ea67413b11cd
Create Date: 2025-12-17 17:47:23.757144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d90685dd4c5'
down_revision: Union[str, Sequence[str], None] = 'ea67413b11cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('source_url', sa.String(length=200), nullable=True))
    op.add_column('pages', sa.Column('scrape_data', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'scrape_data')
    op.drop_column('pages', 'source_url')
    # ### end Alembic commands ###
