"""modifications

Revision ID: 92b58e534f30
Revises: 6c61e3ebe979
Create Date: 2025-12-11 12:57:18.497439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b58e534f30'
down_revision: Union[str, Sequence[str], None] = '6c61e3ebe979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_bg_processes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_run_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cpu_usage', sa.Integer(), nullable=True),
    sa.Column('memory_usage', sa.Integer(), nullable=True),
    sa.Column('process_status', sa.Enum('RUNNING', 'STALLED', 'COMPLETED', 'FAILED', 'TERMINATED', 'CRASHED', name='processstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('content', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'content', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_column('content', 'created_by')
    op.drop_table('task_bg_processes')
    # ### end Alembic commands ###
