"""attachments added to prompt history

Revision ID: 9b2b2aa5a7c9
Revises: 16414c796805
Create Date: 2026-01-21 18:01:31.947298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2b2aa5a7c9'
down_revision: Union[str, Sequence[str], None] = '16414c796805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_attachments', sa.Column('status', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_attachments', 'status')
    # ### end Alembic commands ###
