"""Add pages table and page_id to content table

Revision ID: ea67413b11cd
Revises: ff0e95971dd8
Create Date: 2025-12-16 16:47:43.476673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea67413b11cd'
down_revision: Union[str, Sequence[str], None] = 'ff0e95971dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_page_name'), 'pages', ['page_name'], unique=False)
    op.drop_index(op.f('ix_weaviate_data_versions_changed_at'), table_name='weaviate_data_versions')
    op.drop_index(op.f('ix_weaviate_data_versions_changed_by'), table_name='weaviate_data_versions')
    op.drop_index(op.f('ix_weaviate_data_versions_weaviate_data_id'), table_name='weaviate_data_versions')
    op.drop_table('weaviate_data_versions')
    op.add_column('content', sa.Column('page_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'content', 'pages', ['page_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_column('content', 'page_id')
    op.create_table('weaviate_data_versions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('weaviate_data_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('change_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('old_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('diff', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('operation', sa.VARCHAR(length=50), server_default=sa.text("'UPDATE'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('weaviate_data_versions_changed_by_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['weaviate_data_id'], ['weaviate_data.id'], name=op.f('weaviate_data_versions_weaviate_data_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('weaviate_data_versions_pkey'))
    )
    op.create_index(op.f('ix_weaviate_data_versions_weaviate_data_id'), 'weaviate_data_versions', ['weaviate_data_id'], unique=False)
    op.create_index(op.f('ix_weaviate_data_versions_changed_by'), 'weaviate_data_versions', ['changed_by'], unique=False)
    op.create_index(op.f('ix_weaviate_data_versions_changed_at'), 'weaviate_data_versions', ['changed_at'], unique=False)
    op.drop_index(op.f('ix_pages_page_name'), table_name='pages')
    op.drop_table('pages')
    # ### end Alembic commands ###
