"""modifications

Revision ID: f0afb514de6d
Revises: e5d65752b6c5
Create Date: 2025-12-11 19:03:28.482060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0afb514de6d'
down_revision: Union[str, Sequence[str], None] = 'e5d65752b6c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'task_run_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('content', 'action',
               existing_type=postgresql.ENUM('DRAFT', 'RE_RUN', 'CANCEL', 'STOP', name='contentactionenum'),
               nullable=True)
    op.alter_column('content', 'approval_status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'REVISION_NEEDED', name='contentapprovalstatusenum'),
               nullable=True)
    op.alter_column('content', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('content', 'approval_status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'REVISION_NEEDED', name='contentapprovalstatusenum'),
               nullable=False)
    op.alter_column('content', 'action',
               existing_type=postgresql.ENUM('DRAFT', 'RE_RUN', 'CANCEL', 'STOP', name='contentactionenum'),
               nullable=False)
    op.alter_column('content', 'task_run_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
